---
title: "DZ 3"
author: "Valuta"
date: '8 травня 2019 р '
output: html_document
---


```{r}
library(dplyr)
```



```{r}
{r}
vvv <- c("1.1", "2.2", "3.3", "4.4", "5.5")
```

# Task 1.1
```{r}
fff <- c()
for(e in vvv) {
  append(fff, as.double(e), after = length(fff))
}
```

------

```{r}
vvv_number <- vector ()
i <- 0 
for(e in vvv){
  vvv_number[i] <- as.double(e)
  i <- i+1 
}
```

# Task 1.2
```{r}
vvv2 <- as.double(vvv)
```


###Append
```{r}
vvv3 <- vector ()
i <- 0 
for(e in vvv){
  vvv3 <- append(vvv3, as.double(e))
}
```


#ДОМАШКА2
```{r}
df1 <- df %>%
  mutate(total_area = flat_area + flat_area_family + house_area + house_area_family,
  total_income = income + income_family)
```

```{r}
df2 <- df1 %>%
  filter(total_area > 100, total_income > 1000000)

df3 <- df2 %>% 
  arrange(desc(total_income))
```

```{r}
df4 <- df3 %>% 
  select(full_name, total_area, total_income)
```

```{r}
df_final <- df %>%
  mutate(total_area = flat_area + flat_area_family + house_area + house_area_family,
  total_income = income + income_family) %>% 
  filter(total_area > 100, total_income > 1000000) %>%
  arrange(desc(total_income) ) %>% 
  select(full_name, total_area, total_income)
```


```{r}
rm(df_new)
```




